_BASE_: "Base-Distillation.yaml"
OUTPUT_DIR: output/FCFD-MV2-R50
MODEL:
  BACKBONE:
    NAME: "build_mobilenetv2_fpn_backbone"
    FREEZE_AT: 0
  WEIGHTS: "pretrained/mv2-r50.pth"
  MOBILENETV2:
    OUT_FEATURES: ["m2", "m3", "m4", "m5"]
  FPN:
    IN_FEATURES: ["m2", "m3", "m4", "m5"]

  PROPOSAL_GENERATOR:
    NAME: "RPN"
  ROI_HEADS:
    NAME: "StandardROIHeads"

TEACHER:
  MODEL:
    RESNETS:
      DEPTH: 50
KD:
  TYPE: FCFD
  FCFD:
    ROIL2_WEIGHT: 1.0

SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  MAX_ITER: 180000
  STEPS:
  - 120000
  - 160000
  CHECKPOINT_PERIOD: 60000

TEST:
  EVAL_PERIOD: 5000

VIS_PERIOD: 5000